apiVersion: v1
kind: Pod
metadata:
  name: outcast-pod
  labels:
    app: worker
spec:
  containers:
  - name: nginx
    image: nginx
  tolerations:
  - key: "status"
    operator: "Equal"
    value: "unhealthy"
    effect: "NoSchedule"