apiVersion: apps/v1
kind: Deployment
metadata:
  name: savage-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend-v1
  template:
    metadata:
      labels:
        app: frontend-v2
    spec:
      containers:
      - name: nginx
        image: nginx:latest