apiVersion: v1
kind: ConfigMap
metadata:
  name: status-script
data:
  check-status.sh: |
    #!/bin/sh
    echo "---------------------------------------"
    echo "SavageCamp: Pod is Up and Config Loaded!"
    echo "---------------------------------------"
---
apiVersion: v1
kind: Pod
metadata:
  name: script-checker
spec:
  containers:
  - name: busybox
    image: busybox
    command: ["/bin/sh", "-c", "sh /scripts/check-status.sh && sleep 3600"]
    volumeMounts:
    - name: script-volume
      mountPath: /etc/config/
  volumes:
  - name: script-volume
    configMap:
      name: status-script