apiVersion: v1
kind: Pod
metadata:
  name: web-pod
  namespace: demo-pvc
spec:
  containers:
  - name: web
    image: nginx:latest
    volumeMounts:
    - name: web-data
      mountPath: /usr/share/nginx/html
  volumes:
  - name: web-data
    persistentVolumeClaim:
      claimName: web-pvc
