apiVersion: v1
kind: Namespace
metadata:
  name: demo-pvc
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: web-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /tmp/web-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: web-pvc
  namespace: demo-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: web-pod
  namespace: demo-pvc
spec:
  containers:
  - name: web
    image: nginx:1.27
    volumeMounts:
    - name: web-data
      mountPath: /usr/share/nginx/html
  volumes:
  - name: web-data
    persistentVolumeClaim:
      claimName: web-pvc

