apiVersion: v1
kind: Pod
metadata:
  name: utility-worker
spec:
  containers:
  - name: worker
    image: busybox:latest
    command: ["/bin/sh", "-c", "sleep 3600"]  ### Add this
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"