apiVersion: v1
kind: Pod
metadata:
  name: ready-app
  labels:
    app: health-check
spec:
  containers:
  - name: nginx
    image: nginx:latest
    readinessProbe:
      httpGet:
        path: /   ### Change this from /healthz to /
        port: 80
      initialDelaySeconds: 2
      periodSeconds: 5